params:
  training_experiment: baselines.train_wmd_ad
  validation_metric: best_f1_score
  evaluation_metrics:
    - auc
    - best_f1_score
    - auprc
dataset:
  name: AppleDataset
training_param_updates:
  dataset:
    name: AppleDataset
  training:
    epochs: 1
detector_param_grid:
  detector_params:
    first_diffs:
      - True
      - False
    cum_method:
      - mean
      - max
    feature_index:
      - null
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
    full_cov:
      - True
      - False
