params:
  training_experiment: baselines.train_kmeans
  validation_metric: best_f1_score
  evaluation_metrics:
    - auc
    - best_f1_score
    - auprc
dataset:
  name: AppleDataset
training_param_updates:
  dataset:
    name: AppleDataset
  training:
    epochs: 1
    batch_size: 1024
training_param_grid:
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 1
            - 5
            - 10
            - 25
            - 50
            - 100
          step_size:
            - 1
            - 5
            - 10
detector_param_grid:
  detector_params:
    k:
      - 5
      - 10
      - 50
      - 100

