params:
  training_experiment: reconstruction.train_tcn_ae
  validation_metric: best_f1_score
  evaluation_metrics:
    - auc
    - best_f1_score
    - auprc
dataset:
  name: AppleDataset
training_param_updates:
  dataset:
    name: AppleDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    nb_filters:
      - 20
      - 30
      - 40
    kernel_size:
      - 10
      - 20
    nb_stacks:
      - 1
    dropout_rate:
      - 0.0
      - 0.2
    filters_conv1d:
      - 8
    activation_conv1d:
      - linear
    latent_sample_rate:
      - 42
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 100
            - 120
            - 150
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
