params:
  training_experiment: reconstruction.train_usad
  validation_metric: best_f1_score
  evaluation_metrics:
    - auc
    - best_f1_score
    - auprc
dataset:
  name: AppleDataset
training_param_updates:
  dataset:
    name: AppleDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    z_size:
      - 20
      - 30
      - 40
      - 50
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
detector_param_grid:
  detector_params:
    alpha:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
