params:
  training_experiment: generative.vae.train_donut
  validation_metric: best_f1_score
  evaluation_metrics:
    - auc
    - best_f1_score
    - auprc
dataset:
  name: AppleDataset
training_param_updates:
  dataset:
    name: AppleDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    hidden_dims:
      - [100, 100]
      - [100, 100, 100]
    latent_dim:
      - 20
      - 50
    mask_prob:
      - 0.01
      - 0.03
      - 0.1
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
            - 120
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
detector_param_grid:
  detector_params:
    num_mc_samples:
      - 2
      - 32
      - 64
